/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMobileDetector: typeof import('./components/AppMobileDetector.vue')['default']
    Chart: typeof import('./components/Chart/index.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./components/TabBar.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCounter: typeof import('@varlet/ui')['_CounterComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarPicker: typeof import('@varlet/ui')['_PickerComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarResult: typeof import('@varlet/ui')['_ResultComponent']
    VarSlider: typeof import('@varlet/ui')['_SliderComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
  }
}
